# Generated by Django 3.0.6 on 2020-05-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Power_On', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3)),
                ('Screen_Lightup', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3)),
                ('Device_Works', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3)),
                ('Scratches', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3)),
                ('Crack', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Iphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iphone_model', models.CharField(choices=[('IPhone 11 Pro Max', 'Iphone11Pm'), ('Iphone 11 Pro', 'Iphone11P'), ('Iphone 11', 'Iphone11'), ('Iphone XS Max ', 'Iphonexsm'), ('Iphone XS ', 'Iphonexs'), ('Iphone XR', 'Iphonexr'), ('Iphone X', 'Iphonex'), ('Iphone 8 Plus', 'Iphone8P'), ('Iphone 8', 'Iphone8'), ('Iphone 7 Plus', 'Iphone7P'), ('Iphone 6S Plus', 'Iphone6Sp'), ('Iphone 6s', 'Iphone6S'), ('Iphone 6', 'Iphone6'), ('Iphone SE 2nd Gen', 'Iphonese2'), ('Iphone SE', 'Iphonese')], max_length=30)),
                ('carrier', models.CharField(choices=[('AT&T', 'Att'), ('Verizon', 'Verizon'), ('Tmobile', 'Tmobile'), ('Sprint', 'Sprint'), ('Factory Unlocked', 'Unlocked'), ('Other', 'Other')], max_length=30)),
                ('capacity', models.CharField(choices=[('16 GB', 'Sixteen'), ('32 GB', 'Thiry Two'), ('64 GB', 'Sixty Four'), ('128 GB', 'One Twenty Eight'), ('256 GB', 'Two Fifty Six'), ('512 GB', 'Five Twelve'), ('1 TB', 'One Tb'), ('2 TB', 'Two Tb'), ('4 TB', 'Four Tb')], max_length=30)),
            ],
        ),
    ]
