# Generated by Django 3.0.6 on 2020-06-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ipad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipad_model', models.CharField(choices=[('iPad Pro', 'Ipadpro'), ('iPad Air', 'Ipadair'), ('iPad mini', 'Ipadmini'), ('iPad', 'Ipad')], default=0, max_length=30)),
                ('ipad_generation', models.CharField(choices=[('1st Gen', '1st Gen'), ('2nd Gen', '2nd Gen'), ('3rd Gen', '3rd Gen'), ('4th Gen', '4th Gen'), ('5th Gen', '5th Gen'), ('6th Gen', '6th Gen'), ('7th Gen', '7th Gen')], default=0, max_length=30)),
                ('ipad_capacity', models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB'), ('3 TB', '3 TB'), ('4 TB', '4 TB')], default=0, max_length=30)),
                ('ipad_carrier', models.CharField(choices=[('att', 'AT&T'), ('verizon', 'Verizon'), ('tmobile', 'Tmobile'), ('sprint', 'Sprint'), ('unlocked', 'Factory Unlocked'), ('other', 'Other'), ('wifi', 'Wifi')], default=None, max_length=30)),
                ('ipad_screensize', models.CharField(choices=[('9.7"', '9.7"'), ('10.2"', '10.2"'), ('10.5"', '10.5"'), ('11"', '11"'), ('12.9"', '12.9"')], default=None, max_length=30)),
                ('ipad_condition', models.CharField(choices=[('Broken', 'Broken'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=None, max_length=30)),
                ('offer', models.CharField(default=0, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Iphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iphone_model', models.CharField(choices=[('IPhone 11 Pro Max', 'Iphone11Pm'), ('Iphone 11 Pro', 'Iphone11P'), ('Iphone 11', 'Iphone11'), ('Iphone XS Max ', 'Iphonexsm'), ('Iphone XS ', 'Iphonexs'), ('Iphone XR', 'Iphonexr'), ('Iphone X', 'Iphonex'), ('Iphone 8 Plus', 'Iphone8P'), ('Iphone 8', 'Iphone8'), ('Iphone 7 Plus', 'Iphone7P'), ('Iphone 6S Plus', 'Iphone6Sp'), ('Iphone 6s', 'Iphone6S'), ('Iphone 6', 'Iphone6'), ('Iphone SE 2nd Gen', 'Iphonese2'), ('Iphone SE', 'Iphonese')], default=0, max_length=30)),
                ('carrier', models.CharField(choices=[('att', 'AT&T'), ('verizon', 'Verizon'), ('tmobile', 'Tmobile'), ('sprint', 'Sprint'), ('unlocked', 'Factory Unlocked'), ('other', 'Other'), ('wifi', 'Wifi')], default=None, max_length=30)),
                ('capacity', models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB'), ('3 TB', '3 TB'), ('4 TB', '4 TB')], default=None, max_length=30)),
                ('Offer', models.CharField(default=0, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Macbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Macbook_Model', models.CharField(choices=[('Macbook', 'Mb'), ('Macbook Air', 'Mba'), ('MAcbook Pro', 'Mbp')], default=0, max_length=30)),
                ('Screen_Size', models.CharField(choices=[('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16')], default=0, max_length=30)),
                ('Processer', models.CharField(choices=[('1.1Ghz', '1.1Ghz'), ('1.2Ghz', '1.2Ghz'), ('1.3Ghz', '1.3Ghz'), ('1.4Ghz', '1.4Ghz'), ('1.6Ghz', '1.6Ghz'), ('1.7Ghz', '1.7Ghz'), ('1.8Ghz', '1.8Ghz'), ('2.0Ghz', '2.0Ghz'), ('2.2Ghz', '2.2Ghz'), ('2.3Ghz', '2.3Ghz'), ('2.30Ghz', '2.30Ghz'), ('2.4Ghz', '2.4Ghz'), ('2.5Ghz', '2.5Ghz'), ('2.6Ghz', '2.6Ghz'), ('2.60Ghz', '2.60Ghz'), ('2.7Ghz', '2.7Ghz'), ('2.8Ghz', '2.8Ghz'), ('2.9Ghz', '2.9Ghz'), ('3.0Ghz', '3.0Ghz'), ('3.1Ghz', '3.1Ghz'), ('3.3Ghz', '3.3Ghz'), ('3.5Ghz', '3.5Ghz')], default=0, max_length=30)),
                ('year', models.CharField(choices=[('Mid 2012', 'Mid12'), ('Late 2012', 'Late12'), ('Early 2013', 'Early13'), ('Mid 2013', 'Mid13'), ('Late 2013', 'Late13'), ('Early 2014', 'Early14'), ('Mid 2014', 'Mid14'), ('Early 2015', 'Early15'), ('Mid 2015', 'Mid15'), ('Early 2016', 'Early16'), ('Late 2016', 'Late16'), ('Mid 2017', 'Mid17'), ('Mid 2018', 'Mid18'), ('Late 2018', 'Late18'), ('2019', 'Year2019'), ('Mid 2019', 'Mid19'), ('2020', 'Year2020')], default=0, max_length=30)),
                ('Cosmetic_condition', models.CharField(choices=[('Broken', 'Broken'), ('Fair', 'Fair'), ('Good', 'Good'), ('Flawless', 'Flawless')], default=0, max_length=30)),
                ('offer', models.CharField(default=0, max_length=3)),
            ],
        ),
    ]
