# Generated by Django 3.0.6 on 2020-06-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphone',
            name='condition',
            field=models.CharField(blank=True, choices=[('Broken', 'Broken'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], max_length=30, null=True),
        ),
    ]
