# Generated by Django 3.0.6 on 2020-05-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20200518_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iphone',
            name='Offer',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
