# Generated by Django 3.0.6 on 2020-06-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20200519_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Macbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Macbook_Model', models.CharField(choices=[('Macbook', 'Mb'), ('Macbook Air', 'Mba'), ('MAcbook Pro', 'Mbp')], default=0, max_length=30)),
                ('Screen_Size', models.CharField(choices=[('11"', 'Eleven'), ('13"', 'Thirteen'), ('15"', 'Fifteen'), ('16"', 'Sixteen'), ('17"', 'Seventeen')], default=0, max_length=30)),
                ('Processer', models.CharField(choices=[('1.1Ghz', 'Oneone'), ('1.2Ghz', 'Onetwo'), ('1.3Ghz', 'Onethree'), ('1.4Ghz', 'Onefour'), ('1.6Ghz', 'Onesix'), ('1.7Ghz', 'Oneseven'), ('1.8Ghz', 'Oneeight'), ('2.0Ghz', 'Twozero'), ('2.2Ghz', 'Twotwo'), ('2.3Ghz', 'Twothree'), ('2.30Ghz', 'Twothirty'), ('2.4Ghz', 'Twofour'), ('2.5Ghz', 'Twofive'), ('2.6Ghz', 'Twosix'), ('2.60Ghz', 'Twosixty'), ('2.7Ghz', 'Twoseven'), ('2.8Ghz', 'Twoeight'), ('2.9Ghz', 'Twonine'), ('3.0Ghz', 'Threezero'), ('3.1Ghz', 'Threeone'), ('3.3Ghz', 'Threethree'), ('3.5Ghz', 'Threefive')], default=0, max_length=30)),
                ('year', models.CharField(choices=[('Mid 2012', 'Mid12'), ('Late 2012', 'Late12'), ('Early 2013', 'Early13'), ('Mid 2013', 'Mid13'), ('Late 2013', 'Late13'), ('Early 2014', 'Early14'), ('Mid 2014', 'Mid14'), ('Early 2015', 'Early15'), ('Mid 2015', 'Mid15'), ('Early 2016', 'Early16'), ('Late 2016', 'Late16'), ('Mid 2017', 'Mid17'), ('Mid 2018', 'Mid18'), ('Late 2018', 'Late18'), ('2019', 'Year2019'), ('Mid 2019', 'Mid19'), ('2020', 'Year2020')], default=0, max_length=30)),
                ('Cosmetic_condition', models.CharField(choices=[('Broken', 'Broken'), ('Good', 'Good'), ('Flawless', 'Flawless')], default=0, max_length=30)),
            ],
        ),
    ]
