# Generated by Django 3.0.6 on 2020-06-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20200604_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='GooglePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_model', models.CharField(choices=[('Pixel 4 XL', 'Pixel4Xl'), ('Pixel 4', 'Pixel4'), ('Pixel 3 XL', 'Pixel3Xl'), ('Pixel 3a XL', 'Pixel3Axl'), ('Pixel 3a', 'Pixel3A'), ('Pixel 3', 'Pixel3'), ('Pixel 2 XL', 'Pixel2Xl'), ('Pixel 2', 'Pixel2')], default=0, max_length=30)),
                ('google_capacity', models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB'), ('3 TB', '3 TB'), ('4 TB', '4 TB')], default=0, max_length=30)),
                ('google_carrier', models.CharField(choices=[('att', 'AT&T'), ('verizon', 'Verizon'), ('tmobile', 'Tmobile'), ('sprint', 'Sprint'), ('unlocked', 'Factory Unlocked'), ('other', 'Other'), ('wifi', 'Wifi')], default=None, max_length=30)),
                ('google_condition', models.CharField(choices=[('Broken', 'Broken'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=None, max_length=30)),
                ('offer', models.CharField(default=0, max_length=3)),
            ],
        ),
    ]
