# Generated by Django 3.0.6 on 2020-06-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_googlephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipod_model', models.CharField(choices=[('Touch', 'Touch')], default=0, max_length=30)),
                ('ipod_capacity', models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB'), ('3 TB', '3 TB'), ('4 TB', '4 TB')], default=0, max_length=30)),
                ('ipod_condition', models.CharField(choices=[('Broken', 'Broken'), ('Working%', 'Working'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=None, max_length=30)),
                ('ipod_engraving', models.CharField(choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30)),
                ('offer', models.CharField(default=0, max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='googlephone',
            name='google_condition',
            field=models.CharField(choices=[('Broken', 'Broken'), ('Working%', 'Working'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='ipad',
            name='ipad_condition',
            field=models.CharField(choices=[('Broken', 'Broken'), ('Working%', 'Working'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='condition',
            field=models.CharField(blank=True, choices=[('Broken', 'Broken'), ('Working%', 'Working'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='samsungphone',
            name='samsung_condition',
            field=models.CharField(choices=[('Broken', 'Broken'), ('Working%', 'Working'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=None, max_length=30),
        ),
    ]
