# Generated by Django 3.0.6 on 2020-06-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_macbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macbook',
            name='Cosmetic_condition',
            field=models.CharField(choices=[('Broken', 'Broken'), ('Fair', 'Fair'), ('Good', 'Good'), ('Flawless', 'Flawless')], default=0, max_length=30),
        ),
    ]
