# Generated by Django 3.0.6 on 2020-06-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20200602_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='macbook',
            name='offer',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
