# Generated by Django 3.0.6 on 2020-06-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20200604_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipod',
            name='ipod_generation',
            field=models.CharField(choices=[('1st Gen', '1st Gen'), ('2nd Gen', '2nd Gen'), ('3rd Gen', '3rd Gen'), ('4th Gen', '4th Gen'), ('5th Gen', '5th Gen'), ('6th Gen', '6th Gen'), ('7th Gen', '7th Gen')], default=0, max_length=30),
        ),
    ]
