# Generated by Django 3.0.6 on 2020-06-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_macbook_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macbook',
            name='Processer',
            field=models.CharField(choices=[('1.1Ghz', '1.1Ghz'), ('1.2Ghz', '1.2Ghz'), ('1.3Ghz', '1.3Ghz'), ('1.4Ghz', '1.4Ghz'), ('1.6Ghz', '1.6Ghz'), ('1.7Ghz', '1.7Ghz'), ('1.8Ghz', '1.8Ghz'), ('2.0Ghz', '2.0Ghz'), ('2.2Ghz', '2.2Ghz'), ('2.3Ghz', '2.3Ghz'), ('2.30Ghz', '2.30Ghz'), ('2.4Ghz', '2.4Ghz'), ('2.5Ghz', '2.5Ghz'), ('2.6Ghz', '2.6Ghz'), ('2.60Ghz', '2.60Ghz'), ('2.7Ghz', '2.7Ghz'), ('2.8Ghz', '2.8Ghz'), ('2.9Ghz', '2.9Ghz'), ('3.0Ghz', '3.0Ghz'), ('3.1Ghz', '3.1Ghz'), ('3.3Ghz', '3.3Ghz'), ('3.5Ghz', '3.5Ghz')], default=0, max_length=30),
        ),
    ]
