# Generated by Django 3.0.6 on 2020-06-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20200604_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='iwatch',
            name='iwatch_functional',
            field=models.CharField(choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='iwatch',
            name='iwatch_powercord',
            field=models.CharField(choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='iwatch',
            name='iwatch_carrier',
            field=models.CharField(blank=True, choices=[('att', 'AT&T'), ('verizon', 'Verizon'), ('tmobile', 'Tmobile'), ('sprint', 'Sprint'), ('unlocked', 'Factory Unlocked'), ('other', 'Other'), ('wifi', 'Wifi'), ('wifi Only', 'Wifi Only'), ('wifi + Cellular', 'wifi + Cellular')], default=0, max_length=30, null=True),
        ),
    ]
