# Generated by Django 3.0.6 on 2020-06-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_auto_20200605_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iwatch',
            name='iwatch_functional',
            field=models.CharField(choices=[('Broken', 'Broken'), ('Working%', 'Working'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=None, max_length=30),
        ),
    ]
