# Generated by Django 3.0.6 on 2020-06-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_auto_20200605_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipad',
            name='ipad_screensize',
            field=models.CharField(blank=True, choices=[('9.7"', '9.7"'), ('10.2"', '10.2"'), ('10.5"', '10.5"'), ('11"', '11"'), ('12.9"', '12.9"')], default=None, max_length=30, null=True),
        ),
    ]
