# Generated by Django 3.0.6 on 2020-06-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_auto_20200605_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(choices=[('iPhone', 'iPhone'), ('iPad', 'iPad'), ('iPod', 'iPod'), ('Macbook', 'Macbook'), ('iWatch', 'iWatch'), ('Apple Tv', 'Apple Tv'), ('Android Phones', 'Android Phones'), ('Air Pods', 'Air Pods'), ('PC Laptop', 'PC Laptop'), ('Other', 'Other')], default=0, max_length=30)),
                ('info', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
