# Generated by Django 3.0.6 on 2020-06-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='img_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
