# Generated by Django 3.0.6 on 2020-06-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_auto_20200609_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellBulk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(blank=True, default=0, max_length=30, null=True)),
                ('quantity', models.CharField(blank=True, default=0, max_length=3, null=True)),
                ('description', models.CharField(blank=True, default=0, max_length=300, null=True)),
                ('contact_info', models.CharField(blank=True, default=0, max_length=3, null=True)),
            ],
        ),
    ]
