# Generated by Django 3.0.6 on 2020-07-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_auto_20200712_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlephone',
            name='google_capacity',
            field=models.CharField(choices=[('16 GB', '16'), ('32 GB', '32'), ('64 GB', '64'), ('128 GB', '128'), ('256 GB', '256'), ('512 GB', '512'), ('750 GB', '750'), ('1 TB', '1TB'), ('2 TB', '2TB'), ('4 TB', '4TB')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='ipad',
            name='ipad_capacity',
            field=models.CharField(choices=[('16 GB', '16'), ('32 GB', '32'), ('64 GB', '64'), ('128 GB', '128'), ('256 GB', '256'), ('512 GB', '512'), ('750 GB', '750'), ('1 TB', '1TB'), ('2 TB', '2TB'), ('4 TB', '4TB')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='capacity',
            field=models.CharField(choices=[('16 GB', '16'), ('32 GB', '32'), ('64 GB', '64'), ('128 GB', '128'), ('256 GB', '256'), ('512 GB', '512'), ('750 GB', '750'), ('1 TB', '1TB'), ('2 TB', '2TB'), ('4 TB', '4TB')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='ipod',
            name='ipod_capacity',
            field=models.CharField(choices=[('16 GB', '16'), ('32 GB', '32'), ('64 GB', '64'), ('128 GB', '128'), ('256 GB', '256'), ('512 GB', '512'), ('750 GB', '750'), ('1 TB', '1TB'), ('2 TB', '2TB'), ('4 TB', '4TB')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='samsungphone',
            name='samsung_capacity',
            field=models.CharField(choices=[('16 GB', '16'), ('32 GB', '32'), ('64 GB', '64'), ('128 GB', '128'), ('256 GB', '256'), ('512 GB', '512'), ('750 GB', '750'), ('1 TB', '1TB'), ('2 TB', '2TB'), ('4 TB', '4TB')], default=0, max_length=30),
        ),
    ]
