# Generated by Django 3.0.6 on 2020-07-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_auto_20200712_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iphone',
            name='Offer',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
