# Generated by Django 3.0.6 on 2020-07-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_auto_20200712_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlephone',
            name='google_capacity',
            field=models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB'), ('3 TB', '3 TB'), ('4 TB', '4 TB')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='googlephone',
            name='google_condition',
            field=models.CharField(choices=[('Broken', 'Broken'), ('Working%', 'Working'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='ipad',
            name='ipad_capacity',
            field=models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB'), ('3 TB', '3 TB'), ('4 TB', '4 TB')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='ipad',
            name='ipad_condition',
            field=models.CharField(choices=[('Broken', 'Broken'), ('Working%', 'Working'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='Offer',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='capacity',
            field=models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB'), ('3 TB', '3 TB'), ('4 TB', '4 TB')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='condition',
            field=models.CharField(blank=True, choices=[('Broken', 'Broken'), ('Working%', 'Working'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='iphone_model',
            field=models.CharField(choices=[('IPhone 11 Pro Max', 'Iphone11Pm'), ('Iphone 11 Pro', 'Iphone11P'), ('Iphone 11', 'Iphone11'), ('Iphone XS Max ', 'Iphonexsm'), ('Iphone XS ', 'Iphonexs'), ('Iphone XR', 'Iphonexr'), ('Iphone X', 'Iphonex'), ('Iphone 8 Plus', 'Iphone8P'), ('Iphone 8', 'Iphone8'), ('Iphone 7 Plus', 'Iphone7P'), ('Iphone 6S Plus', 'Iphone6Sp'), ('Iphone 6s', 'Iphone6S'), ('Iphone 6', 'Iphone6'), ('Iphone SE 2nd Gen', 'Iphonese2'), ('Iphone SE', 'Iphonese')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='ipod',
            name='ipod_capacity',
            field=models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB'), ('3 TB', '3 TB'), ('4 TB', '4 TB')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='ipod',
            name='ipod_condition',
            field=models.CharField(choices=[('Broken', 'Broken'), ('Working%', 'Working'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='iwatch',
            name='iwatch_condition',
            field=models.CharField(choices=[('Broken', 'Broken'), ('Working%', 'Working'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='iwatch',
            name='iwatch_functional',
            field=models.CharField(choices=[('Broken', 'Broken'), ('Working%', 'Working'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='samsungphone',
            name='samsung_capacity',
            field=models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB'), ('3 TB', '3 TB'), ('4 TB', '4 TB')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='samsungphone',
            name='samsung_condition',
            field=models.CharField(choices=[('Broken', 'Broken'), ('Working%', 'Working'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=None, max_length=30),
        ),
    ]
