# Generated by Django 3.0.6 on 2020-07-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_auto_20200716_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlephone',
            name='google_model',
            field=models.CharField(choices=[('Pixel 4 XL', 'Pixel 4 XL'), ('Pixel 4', 'Pixel 4'), ('Pixel 3 XL', 'Pixel 3 XL'), ('Pixel 3a XL', 'Pixel 3a XL'), ('Pixel 3a', 'Pixel 3a'), ('Pixel 3', 'Pixel 3'), ('Pixel 2 XL', 'Pixel 2 XL'), ('Pixel 2', 'Pixel 2')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='ipad',
            name='ipad_model',
            field=models.CharField(choices=[('iPadPro', 'iPad Pro'), ('ipadAir', 'iPad Air'), ('iPadMini', 'iPad mini'), ('iPad', 'iPad')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='iphone_model',
            field=models.CharField(choices=[('IPhone 11 Pro Max', 'IPhone 11 Pro Max'), ('Iphone 11 Pro', 'Iphone 11 Pro'), ('Iphone 11', 'Iphone 11'), ('Iphone XS Max', 'Iphone XS Max'), ('Iphone XS', 'Iphone XS'), ('Iphone XR', 'Iphone XR'), ('Iphone X', 'Iphone X'), ('Iphone 8 Plus', 'Iphone 8 Plus'), ('Iphone 8', 'Iphone 8'), ('Iphone 7 Plus', 'Iphone 7 Plus'), ('Iphone 6S Plus', 'Iphone 6S Plus'), ('Iphone 6s', 'Iphone 6s'), ('Iphone 6', 'Iphone 6'), ('Iphone SE 2nd Gen', 'Iphone SE 2nd Gen'), ('Iphone SE', 'Iphone SE')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='iwatch',
            name='iwatch_model',
            field=models.CharField(choices=[('Apple Watch Original', 'Apple Watch Original'), ('Apple Watch Series 1', 'Apple Watch Series 1'), ('Apple Watch Series 2', 'Apple Watch Series 2'), ('Apple Watch Series 3', 'Apple Watch Series 3'), ('Apple Watch Series 4', 'Apple Watch Series 4'), ('Apple Watch Series 5', 'Apple Watch Series 5')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='macbook',
            name='Cosmetic_condition',
            field=models.CharField(choices=[('Broken', 'Broken'), ('Fair', 'Fair'), ('GooD', 'Good'), ('Flawless', 'Flawless')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='macbook',
            name='Macbook_Model',
            field=models.CharField(choices=[('Mid 2012', 'Mid 2012'), ('Late 2012', 'Late 2012'), ('Early 2013', 'Early 2013'), ('Mid 2013', 'Mid 2013'), ('Late 2013', 'Late 2013'), ('Early 2014', 'Early 2014'), ('Mid 2014', 'Mid 2014'), ('Early 2015', 'Early 2015'), ('Mid 2015', 'Mid 2015'), ('Early 2016', 'Early 2016'), ('Late 2016', 'Late 2016'), ('Mid 2017', 'Mid 2017'), ('Mid 2018', 'Mid 2018'), ('Late 2018', 'Late 2018'), ('2019', '2019'), ('Mid 2019', 'Mid 2019'), ('2020', '2020')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='macbook',
            name='year',
            field=models.CharField(choices=[('Mid 2012', 'Mid 2012'), ('Late 2012', 'Late 2012'), ('Early 2013', 'Early 2013'), ('Mid 2013', 'Mid 2013'), ('Late 2013', 'Late 2013'), ('Early 2014', 'Early 2014'), ('Mid 2014', 'Mid 2014'), ('Early 2015', 'Early 2015'), ('Mid 2015', 'Mid 2015'), ('Early 2016', 'Early 2016'), ('Late 2016', 'Late 2016'), ('Mid 2017', 'Mid 2017'), ('Mid 2018', 'Mid 2018'), ('Late 2018', 'Late 2018'), ('2019', '2019'), ('Mid 2019', 'Mid 2019'), ('2020', '2020')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='samsungphone',
            name='samsung_model',
            field=models.CharField(choices=[('Galaxy Z-Flip', 'Galaxy Z-Flip'), ('Galaxy Fold SM-F900', 'Galaxy Fold SM-F900'), ('Galaxy Note 10+ SM-N975', 'Galaxy Note 10+ SM-N975'), ('Galaxy Note 10 SM-N970', 'Galaxy Note 10 SM-N970'), ('Galaxy S10+', 'Galaxy S10+'), ('Galaxy S10', 'Galaxy S10'), ('Galaxy S10e', 'Galaxy S10e'), ('Galaxy Note 9 SM-N960', 'Galaxy Note 9 SM-N960'), ('Galaxy S9+ SM-G965A', 'Galaxy S9+ SM-G965A'), ('Galaxy S9 SM-G960A', 'Galaxy S9 SM-G960A'), ('Galaxy S8+ SM-G955A', 'Galaxy S8+ SM-G955A'), ('GalaxyS8SMG950A', 'GalaxyS8SMG950A'), ('Galaxy S8 Active SM-G892A', 'Galaxy S8 Active SM-G892A'), ('Galaxy Note 8 SM-N950A', 'Galaxy Note 8 SM-N950A'), ('Galaxy S7 edge SM-G935A', 'Galaxy S7 edge SM-G935A'), ('Galaxy S7 SM-G930A', 'Galaxy S7 SM-G930A'), ('Galaxy S6 edge+ SM-G928', 'Galaxy S6 edge+SM-G928'), ('Galaxy S6 Edge SM-G925V', 'Galaxy S6 Edge SM-G925V'), ('Galaxy S20', 'Galaxy S20'), ('Galaxy S20 Ultra', 'Galaxy S20 Ultra'), ('Galaxy S20+', 'Galaxy S20+')], default=0, max_length=30),
        ),
    ]
