# Generated by Django 2.2.10 on 2020-07-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_auto_20200720_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlephone',
            name='google_capacity',
            field=models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB'), ('3 TB', '3 TB'), ('4 TB', '4 TB'), ('not known', "Don't Know")], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='googlephone',
            name='google_carrier',
            field=models.CharField(choices=[('att', 'AT&T'), ('verizon', 'Verizon'), ('tmobile', 'Tmobile'), ('sprint', 'Sprint'), ('unlocked', 'Factory Unlocked'), ('other', 'Other'), ('not known', "Don't Know"), ('wifi', 'Wifi'), ('wifi Only', 'Wifi Only'), ('wifi + Cellular', 'wifi + Cellular')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='ipad',
            name='ipad_capacity',
            field=models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB'), ('3 TB', '3 TB'), ('4 TB', '4 TB'), ('not known', "Don't Know")], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='ipad',
            name='ipad_carrier',
            field=models.CharField(choices=[('att', 'AT&T'), ('verizon', 'Verizon'), ('tmobile', 'Tmobile'), ('sprint', 'Sprint'), ('unlocked', 'Factory Unlocked'), ('other', 'Other'), ('not known', "Don't Know"), ('wifi', 'Wifi'), ('wifi Only', 'Wifi Only'), ('wifi + Cellular', 'wifi + Cellular')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='capacity',
            field=models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB'), ('3 TB', '3 TB'), ('4 TB', '4 TB'), ('not known', "Don't Know")], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='carrier',
            field=models.CharField(choices=[('att', 'AT&T'), ('verizon', 'Verizon'), ('tmobile', 'Tmobile'), ('sprint', 'Sprint'), ('unlocked', 'Factory Unlocked'), ('other', 'Other'), ('not known', "Don't Know"), ('wifi', 'Wifi'), ('wifi Only', 'Wifi Only'), ('wifi + Cellular', 'wifi + Cellular')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='ipod',
            name='ipod_capacity',
            field=models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB'), ('3 TB', '3 TB'), ('4 TB', '4 TB'), ('not known', "Don't Know")], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='iwatch',
            name='iwatch_carrier',
            field=models.CharField(blank=True, choices=[('att', 'AT&T'), ('verizon', 'Verizon'), ('tmobile', 'Tmobile'), ('sprint', 'Sprint'), ('unlocked', 'Factory Unlocked'), ('other', 'Other'), ('not known', "Don't Know"), ('wifi', 'Wifi'), ('wifi Only', 'Wifi Only'), ('wifi + Cellular', 'wifi + Cellular')], default=0, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='macbook',
            name='Macbook_Model',
            field=models.CharField(choices=[('Macbook', 'Macbook'), ('Macbook Air', 'Macbook Air'), ('MAcbook Pro', 'MAcbook Pro')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='samsungphone',
            name='samsung_capacity',
            field=models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB'), ('3 TB', '3 TB'), ('4 TB', '4 TB'), ('not known', "Don't Know")], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='samsungphone',
            name='samsung_carrier',
            field=models.CharField(choices=[('att', 'AT&T'), ('verizon', 'Verizon'), ('tmobile', 'Tmobile'), ('sprint', 'Sprint'), ('unlocked', 'Factory Unlocked'), ('other', 'Other'), ('not known', "Don't Know"), ('wifi', 'Wifi'), ('wifi Only', 'Wifi Only'), ('wifi + Cellular', 'wifi + Cellular')], default=None, max_length=30),
        ),
    ]
