# Generated by Django 2.2.10 on 2020-07-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_auto_20200722_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='macbook',
            old_name='Cosmetic_condition',
            new_name='cosmetic_condition',
        ),
        migrations.RenameField(
            model_name='macbook',
            old_name='Processer',
            new_name='processer',
        ),
        migrations.RenameField(
            model_name='macbook',
            old_name='Screen_Size',
            new_name='screen_Size',
        ),
        migrations.AddField(
            model_name='macbook',
            name='storage_capacity',
            field=models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB SSD', '128GB SSD'), ('128 GB ', '128 GB '), ('256 GB', '256 GB'), ('256 GB SSD', '256 GB SSD'), ('512 GB', '512 GB'), ('512 GB SSD', '512 GB'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('1 TB SSD', '1 TB SSD'), ('2 TB SSD', '2 TB SSD'), ('3 TB SSD', '3 TB SSD'), ('4 TB SSD', '4 TB SSD'), ('not known', "Don't Know")], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='googlephone',
            name='google_capacity',
            field=models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB SSD', '128GB SSD'), ('128 GB ', '128 GB '), ('256 GB', '256 GB'), ('256 GB SSD', '256 GB SSD'), ('512 GB', '512 GB'), ('512 GB SSD', '512 GB'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('1 TB SSD', '1 TB SSD'), ('2 TB SSD', '2 TB SSD'), ('3 TB SSD', '3 TB SSD'), ('4 TB SSD', '4 TB SSD'), ('not known', "Don't Know")], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='ipad',
            name='ipad_capacity',
            field=models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB SSD', '128GB SSD'), ('128 GB ', '128 GB '), ('256 GB', '256 GB'), ('256 GB SSD', '256 GB SSD'), ('512 GB', '512 GB'), ('512 GB SSD', '512 GB'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('1 TB SSD', '1 TB SSD'), ('2 TB SSD', '2 TB SSD'), ('3 TB SSD', '3 TB SSD'), ('4 TB SSD', '4 TB SSD'), ('not known', "Don't Know")], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='capacity',
            field=models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB SSD', '128GB SSD'), ('128 GB ', '128 GB '), ('256 GB', '256 GB'), ('256 GB SSD', '256 GB SSD'), ('512 GB', '512 GB'), ('512 GB SSD', '512 GB'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('1 TB SSD', '1 TB SSD'), ('2 TB SSD', '2 TB SSD'), ('3 TB SSD', '3 TB SSD'), ('4 TB SSD', '4 TB SSD'), ('not known', "Don't Know")], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='ipod',
            name='ipod_capacity',
            field=models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB SSD', '128GB SSD'), ('128 GB ', '128 GB '), ('256 GB', '256 GB'), ('256 GB SSD', '256 GB SSD'), ('512 GB', '512 GB'), ('512 GB SSD', '512 GB'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('1 TB SSD', '1 TB SSD'), ('2 TB SSD', '2 TB SSD'), ('3 TB SSD', '3 TB SSD'), ('4 TB SSD', '4 TB SSD'), ('not known', "Don't Know")], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='samsungphone',
            name='samsung_capacity',
            field=models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB SSD', '128GB SSD'), ('128 GB ', '128 GB '), ('256 GB', '256 GB'), ('256 GB SSD', '256 GB SSD'), ('512 GB', '512 GB'), ('512 GB SSD', '512 GB'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('1 TB SSD', '1 TB SSD'), ('2 TB SSD', '2 TB SSD'), ('3 TB SSD', '3 TB SSD'), ('4 TB SSD', '4 TB SSD'), ('not known', "Don't Know")], default=0, max_length=30),
        ),
    ]
