# Generated by Django 2.2.10 on 2020-07-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_auto_20200722_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iphone',
            name='iphone_model',
            field=models.CharField(choices=[('IPhone 11 Pro Max', 'IPhone 11 Pro Max'), ('Iphone 11 Pro', 'Iphone 11 Pro'), ('Iphone 11', 'Iphone 11'), ('Iphone XS Max', 'Iphone XS Max'), ('Iphone XS', 'Iphone XS'), ('Iphone XR', 'Iphone XR'), ('Iphone X', 'Iphone X'), ('Iphone 8 Plus', 'Iphone 8 Plus'), ('Iphone 8', 'Iphone 8'), ('Iphone 7 Plus', 'Iphone 7 Plus'), ('Iphone 7 ', 'Iphone 7'), ('Iphone 6S Plus', 'Iphone 6S Plus'), ('Iphone 6s', 'Iphone 6s'), ('Iphone 6', 'Iphone 6'), ('Iphone SE 2nd Gen', 'Iphone SE 2nd Gen'), ('Iphone SE', 'Iphone SE')], default=0, max_length=30),
        ),
    ]
