# Generated by Django 2.2.10 on 2020-07-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0023_auto_20200724_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airpods',
            name='charging_case',
            field=models.CharField(blank=True, choices=[('Wireless charging case', 'Wireless charging case'), ('Wired charging case', 'Wired charging case'), ('Don’t have idea', 'Don’t have idea')], default=0, max_length=30, null=True),
        ),
    ]
