# Generated by Django 2.2.10 on 2020-07-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0025_auto_20200724_0559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airpods',
        ),
    ]
