# Generated by Django 2.2.10 on 2020-07-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0027_auto_20200724_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='airpods',
            name='offer',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
