# Generated by Django 2.2.10 on 2020-07-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0029_auto_20200724_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='samsungphone',
            name='samsung_box',
            field=models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='samsungphone',
            name='samsung_functional',
            field=models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='samsungphone',
            name='samsung_headset',
            field=models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='samsungphone',
            name='samsung_isunlock',
            field=models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='samsungphone',
            name='samsung_powercord',
            field=models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='googlephone',
            name='google_carrier',
            field=models.CharField(choices=[('att', 'AT&T'), ('verizon', 'Verizon'), ('tmobile', 'Tmobile'), ('sprint', 'Sprint'), ('unlocked', 'Factory Unlocked'), ('other', 'Other'), ('not known', "Don't Know"), ('wifi', 'Wifi'), ('wifi Only', 'Wifi Only'), ('GPS', 'GPS'), ('GPS + Cellular', 'GPS + Cellular'), ('U.S Cellular', 'U.S Cellular'), ('Xfinity', 'Xfinity'), ('Cricket', 'Cricket')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='ipad',
            name='ipad_carrier',
            field=models.CharField(choices=[('att', 'AT&T'), ('verizon', 'Verizon'), ('tmobile', 'Tmobile'), ('sprint', 'Sprint'), ('unlocked', 'Factory Unlocked'), ('other', 'Other'), ('not known', "Don't Know"), ('wifi', 'Wifi'), ('wifi Only', 'Wifi Only'), ('GPS', 'GPS'), ('GPS + Cellular', 'GPS + Cellular'), ('U.S Cellular', 'U.S Cellular'), ('Xfinity', 'Xfinity'), ('Cricket', 'Cricket')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='carrier',
            field=models.CharField(choices=[('att', 'AT&T'), ('verizon', 'Verizon'), ('tmobile', 'Tmobile'), ('sprint', 'Sprint'), ('unlocked', 'Factory Unlocked'), ('other', 'Other'), ('not known', "Don't Know"), ('wifi', 'Wifi'), ('wifi Only', 'Wifi Only'), ('GPS', 'GPS'), ('GPS + Cellular', 'GPS + Cellular'), ('U.S Cellular', 'U.S Cellular'), ('Xfinity', 'Xfinity'), ('Cricket', 'Cricket')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='iwatch',
            name='iwatch_carrier',
            field=models.CharField(blank=True, choices=[('att', 'AT&T'), ('verizon', 'Verizon'), ('tmobile', 'Tmobile'), ('sprint', 'Sprint'), ('unlocked', 'Factory Unlocked'), ('other', 'Other'), ('not known', "Don't Know"), ('wifi', 'Wifi'), ('wifi Only', 'Wifi Only'), ('GPS', 'GPS'), ('GPS + Cellular', 'GPS + Cellular'), ('U.S Cellular', 'U.S Cellular'), ('Xfinity', 'Xfinity'), ('Cricket', 'Cricket')], default=0, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='samsungphone',
            name='samsung_carrier',
            field=models.CharField(choices=[('att', 'AT&T'), ('verizon', 'Verizon'), ('tmobile', 'Tmobile'), ('sprint', 'Sprint'), ('unlocked', 'Factory Unlocked'), ('other', 'Other'), ('not known', "Don't Know"), ('wifi', 'Wifi'), ('wifi Only', 'Wifi Only'), ('GPS', 'GPS'), ('GPS + Cellular', 'GPS + Cellular'), ('U.S Cellular', 'U.S Cellular'), ('Xfinity', 'Xfinity'), ('Cricket', 'Cricket')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='samsungphone',
            name='samsung_model',
            field=models.CharField(choices=[('Galaxy Fold', 'Galaxy Fold'), ('Galaxy Z-Flip', 'Galaxy Z-Flip'), ('Galaxy Fold SM-F900', 'Galaxy Fold SM-F900'), ('Galaxy Note 10+ 5G', 'Galaxy Note 10+ 5G'), ('Galaxy Note 10+', 'Galaxy Note 10+'), ('Galaxy Note 10', 'Galaxy Note 10'), ('Galaxy Note 9', 'Galaxy Note 9'), ('Galaxy Note 8', 'Galaxy Note 8'), ('Galaxy S10+', 'Galaxy S10+'), ('Galaxy S10', 'Galaxy S10'), ('Galaxy S10 5G', 'Galaxy S10 5G'), ('Galaxy S10 Lite', 'Galaxy S10 Lite'), ('Galaxy S10e', 'Galaxy S10e'), ('Galaxy S9+', 'Galaxy S9+'), ('Galaxy S9', 'Galaxy S9'), ('Galaxy S8+', 'Galaxy S8+'), ('Galaxy S8 Active', 'Galaxy S8 Active'), ('Galaxy S8', 'Galaxy S8'), ('Galaxy S7 Edge', 'Galaxy S7 Edge'), ('Galaxy S7', 'Galaxy S7'), ('Galaxy S6 Edge+', 'Galaxy S6 Edge+'), ('Galaxy S6 Edge', 'Galaxy S6 Edge'), ('Galaxy S6', 'Galaxy S6'), ('Galaxy S20 5G', 'Galaxy S20 5G'), ('Galaxy S20 Ultra 5G', 'Galaxy S20 Ultra 5G'), ('Galaxy S20+ 5G', 'Galaxy S20+ 5G')], default=0, max_length=30),
        ),
    ]
