# Generated by Django 2.2.10 on 2020-07-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0030_auto_20200729_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlephone',
            name='google_box',
            field=models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='googlephone',
            name='google_functional',
            field=models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='googlephone',
            name='google_headset',
            field=models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='googlephone',
            name='google_powercord',
            field=models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='googlephone',
            name='google_capacity',
            field=models.CharField(blank=True, choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB SSD', '128GB SSD'), ('128 GB ', '128 GB '), ('256 GB', '256 GB'), ('256 GB SSD', '256 GB SSD'), ('512 GB', '512 GB'), ('512 GB SSD', '512 GB'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('1 TB SSD', '1 TB SSD'), ('2 TB SSD', '2 TB SSD'), ('3 TB SSD', '3 TB SSD'), ('4 TB SSD', '4 TB SSD'), ('not known', "Don't Know")], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='googlephone',
            name='google_carrier',
            field=models.CharField(blank=True, choices=[('att', 'AT&T'), ('verizon', 'Verizon'), ('tmobile', 'Tmobile'), ('sprint', 'Sprint'), ('unlocked', 'Factory Unlocked'), ('other', 'Other'), ('not known', "Don't Know"), ('wifi', 'Wifi'), ('wifi Only', 'Wifi Only'), ('GPS', 'GPS'), ('GPS + Cellular', 'GPS + Cellular'), ('U.S Cellular', 'U.S Cellular'), ('Xfinity', 'Xfinity'), ('Cricket', 'Cricket')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='googlephone',
            name='google_condition',
            field=models.CharField(blank=True, choices=[('Broken', 'Broken'), ('Working%', 'Working'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='googlephone',
            name='offer',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='ipad',
            name='offer',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='macbook',
            name='offer',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='samsungphone',
            name='offer',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='samsungphone',
            name='samsung_capacity',
            field=models.CharField(blank=True, choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB SSD', '128GB SSD'), ('128 GB ', '128 GB '), ('256 GB', '256 GB'), ('256 GB SSD', '256 GB SSD'), ('512 GB', '512 GB'), ('512 GB SSD', '512 GB'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('1 TB SSD', '1 TB SSD'), ('2 TB SSD', '2 TB SSD'), ('3 TB SSD', '3 TB SSD'), ('4 TB SSD', '4 TB SSD'), ('not known', "Don't Know")], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='samsungphone',
            name='samsung_carrier',
            field=models.CharField(blank=True, choices=[('att', 'AT&T'), ('verizon', 'Verizon'), ('tmobile', 'Tmobile'), ('sprint', 'Sprint'), ('unlocked', 'Factory Unlocked'), ('other', 'Other'), ('not known', "Don't Know"), ('wifi', 'Wifi'), ('wifi Only', 'Wifi Only'), ('GPS', 'GPS'), ('GPS + Cellular', 'GPS + Cellular'), ('U.S Cellular', 'U.S Cellular'), ('Xfinity', 'Xfinity'), ('Cricket', 'Cricket')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='samsungphone',
            name='samsung_condition',
            field=models.CharField(blank=True, choices=[('Broken', 'Broken'), ('Working%', 'Working'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=None, max_length=30, null=True),
        ),
    ]
