# Generated by Django 2.2.10 on 2020-08-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0033_auto_20200807_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macbook',
            name='other',
        ),
        migrations.AddField(
            model_name='macbook',
            name='battery_health',
            field=models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Broken', 'Broken'), ('Fair', 'Fair'), ('Good', 'Good'), ('Flawless', 'Flawless')], default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='macbook',
            name='graphics_card',
            field=models.CharField(blank=True, choices=[('1.1Ghz i3', '1.1Ghz i3'), ('1.1Ghz i5', '1.1Ghz i5'), ('Dedicated Graphics', 'Dedicated Graphics'), ('Retina', 'Retina'), ('No Retina', 'No Retina'), ('Touch Vega', 'Touch Vega'), ('Touch', 'Touch'), ('AMD Radeon R9 M370X Graphics', 'AMD Radeon R9 M370X Graphics'), ('Nvidia Geforce GT 750 Graphics', 'Nvidia Geforce GT 750 Graphics'), ('AMD Radeon Pro 555X', 'AMD Radeon Pro 555X'), ('AMD Radeon Pro 560X', 'AMD Radeon Pro 560X'), ('AMD Radeon Pro Vega 16', 'AMD Radeon Pro Vega 16'), ('AMD Radeon Pro Vega 20', 'AMD Radeon Pro Vega 20'), ('AMD Radeon Pro 5300M w/4GB', 'AMD Radeon Pro 5300M w/4GB'), ('AMD Radeon Pro 5500M w/4GB', 'AMD Radeon Pro 5500M w/4GB'), ('AMD Radeon Pro 5500M w/8GB', 'AMD Radeon Pro 5500M w/8GB'), ('AMD Radeon Pro 5600M w/8GB HBM2', 'AMD Radeon Pro 5600M w/8GB HBM2')], default=0, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='macbook',
            name='touch',
            field=models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='airpods',
            name='airpods_condition',
            field=models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Broken', 'Broken'), ('Fair', 'Fair'), ('Good', 'Good'), ('Flawless', 'Flawless')], default=0, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='macbook',
            name='processer',
            field=models.CharField(blank=True, choices=[('1.1Ghz', '1.1Ghz'), ('M 1.1Ghz', 'M 1.1Ghz'), ('M 1.2Ghz', 'M 1.2Ghz'), ('M 1.3Ghz', 'M 1.3Ghz'), ('m3 1.1Ghz', 'm3 1.1Ghz'), ('m5 1.2Ghz', 'm5 1.2Ghz'), ('m7 1.3Ghz', 'm7 1.3Ghz'), ('m3 1.2Ghz', 'm3 1.2Ghz'), ('i5 1.3Ghz ', 'i5 1.3Ghz'), ('i7 1.4Ghz', 'i7 1.4Ghz'), ('i5', 'i5'), ('i7', 'i7'), ('1.2Ghz', '1.2Ghz'), ('1.3 i5 Ghz', '1.3 i5Ghz'), ('1.4Ghz', '1.4Ghz'), ('1.3Ghz', '1.3Ghz'), ('1.4Ghz', '1.4Ghz'), ('1.6Ghz', '1.6Ghz'), ('1.7Ghz', '1.7Ghz'), ('1.8Ghz', '1.8Ghz'), ('2.0Ghz', '2.0Ghz'), ('2.2Ghz', '2.2Ghz'), ('2.3Ghz', '2.3Ghz'), ('2.30Ghz', '2.30Ghz'), ('2.4Ghz', '2.4Ghz'), ('2.5Ghz', '2.5Ghz'), ('2.6Ghz', '2.6Ghz'), ('2.60Ghz', '2.60Ghz'), ('2.7Ghz', '2.7Ghz'), ('2.8Ghz', '2.8Ghz'), ('2.9Ghz', '2.9Ghz'), ('3.0Ghz', '3.0Ghz'), ('3.1Ghz', '3.1Ghz'), ('3.3Ghz', '3.3Ghz'), ('3.5Ghz', '3.5Ghz')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='macbook',
            name='year',
            field=models.CharField(blank=True, choices=[('Mid 2012', 'Mid 2012'), ('Late 2012', 'Late 2012'), ('Early 2013', 'Early 2013'), ('Mid 2013', 'Mid 2013'), ('Late 2013', 'Late 2013'), ('Early 2014', 'Early 2014'), ('Mid 2014', 'Mid 2014'), ('Early 2015', 'Early 2015'), ('Mid 2015', 'Mid 2015'), ('Early 2016', 'Early 2016'), ('Late 2016', 'Late 2016'), ('2016', '2016'), ('2017', '2017'), ('Mid 2017', 'Mid 2017'), ('Mid 2018', 'Mid 2018'), ('Late 2018', 'Late 2018'), ('2019', '2019'), ('Mid 2019', 'Mid 2019'), ('2020', '2020')], default=None, max_length=30, null=True),
        ),
    ]
