# Generated by Django 2.2.10 on 2020-08-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0035_auto_20200809_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlephone',
            name='google_capacity',
            field=models.CharField(blank=True, choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('64 GB SSD', '64 GB SSD'), ('80 GB', '80 GB'), ('120 GB ', '12O GB '), ('128 GB SSD', '128GB SSD'), ('128 GB ', '128 GB '), ('256 GB', '256 GB'), ('256 GB SSD', '256 GB SSD'), ('512 GB', '512 GB'), ('512 GB SSD', '512 GB SSD'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('1.5 TB', '1.5 TB'), ('1 TB SSD', '1 TB SSD'), ('2 TB SSD', '2 TB SSD'), ('3 TB SSD', '3 TB SSD'), ('4 TB SSD', '4 TB SSD'), ('not known', "Don't Know")], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ipad',
            name='ipad_capacity',
            field=models.CharField(choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('64 GB SSD', '64 GB SSD'), ('80 GB', '80 GB'), ('120 GB ', '12O GB '), ('128 GB SSD', '128GB SSD'), ('128 GB ', '128 GB '), ('256 GB', '256 GB'), ('256 GB SSD', '256 GB SSD'), ('512 GB', '512 GB'), ('512 GB SSD', '512 GB SSD'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('1.5 TB', '1.5 TB'), ('1 TB SSD', '1 TB SSD'), ('2 TB SSD', '2 TB SSD'), ('3 TB SSD', '3 TB SSD'), ('4 TB SSD', '4 TB SSD'), ('not known', "Don't Know")], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='capacity',
            field=models.CharField(choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('64 GB SSD', '64 GB SSD'), ('80 GB', '80 GB'), ('120 GB ', '12O GB '), ('128 GB SSD', '128GB SSD'), ('128 GB ', '128 GB '), ('256 GB', '256 GB'), ('256 GB SSD', '256 GB SSD'), ('512 GB', '512 GB'), ('512 GB SSD', '512 GB SSD'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('1.5 TB', '1.5 TB'), ('1 TB SSD', '1 TB SSD'), ('2 TB SSD', '2 TB SSD'), ('3 TB SSD', '3 TB SSD'), ('4 TB SSD', '4 TB SSD'), ('not known', "Don't Know")], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='ipod',
            name='ipod_capacity',
            field=models.CharField(choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('64 GB SSD', '64 GB SSD'), ('80 GB', '80 GB'), ('120 GB ', '12O GB '), ('128 GB SSD', '128GB SSD'), ('128 GB ', '128 GB '), ('256 GB', '256 GB'), ('256 GB SSD', '256 GB SSD'), ('512 GB', '512 GB'), ('512 GB SSD', '512 GB SSD'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('1.5 TB', '1.5 TB'), ('1 TB SSD', '1 TB SSD'), ('2 TB SSD', '2 TB SSD'), ('3 TB SSD', '3 TB SSD'), ('4 TB SSD', '4 TB SSD'), ('not known', "Don't Know")], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='macbook',
            name='processer',
            field=models.CharField(blank=True, choices=[('Core 2 Duo', 'Core 2 Duo'), ('1.1Ghz', '1.1Ghz'), ('M 1.1Ghz', 'M 1.1Ghz'), ('M 1.2Ghz', 'M 1.2Ghz'), ('M 1.3Ghz', 'M 1.3Ghz'), ('m3 1.1Ghz', 'm3 1.1Ghz'), ('m5 1.2Ghz', 'm5 1.2Ghz'), ('m7 1.3Ghz', 'm7 1.3Ghz'), ('m3 1.2Ghz', 'm3 1.2Ghz'), ('i5 1.3Ghz ', 'i5 1.3Ghz'), ('i7 1.4Ghz', 'i7 1.4Ghz'), ('i5', 'i5'), ('i7', 'i7'), ('1.2Ghz', '1.2Ghz'), ('1.3 i5 Ghz', '1.3 i5Ghz'), ('1.4Ghz', '1.4Ghz'), ('1.3Ghz', '1.3Ghz'), ('1.4Ghz', '1.4Ghz'), ('1.6Ghz', '1.6Ghz'), ('1.7Ghz', '1.7Ghz'), ('1.8Ghz', '1.8Ghz'), ('2.0Ghz', '2.0Ghz'), ('2.2Ghz', '2.2Ghz'), ('2.3Ghz', '2.3Ghz'), ('2.30Ghz', '2.30Ghz'), ('2.4Ghz', '2.4Ghz'), ('2.5Ghz', '2.5Ghz'), ('2.6Ghz', '2.6Ghz'), ('2.60Ghz', '2.60Ghz'), ('2.7Ghz', '2.7Ghz'), ('2.8Ghz', '2.8Ghz'), ('2.9Ghz', '2.9Ghz'), ('3.0Ghz', '3.0Ghz'), ('3.1Ghz', '3.1Ghz'), ('3.3Ghz', '3.3Ghz'), ('3.5Ghz', '3.5Ghz')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='macbook',
            name='ram_capacity',
            field=models.CharField(blank=True, choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('64 GB SSD', '64 GB SSD'), ('80 GB', '80 GB'), ('120 GB ', '12O GB '), ('128 GB SSD', '128GB SSD'), ('128 GB ', '128 GB '), ('256 GB', '256 GB'), ('256 GB SSD', '256 GB SSD'), ('512 GB', '512 GB'), ('512 GB SSD', '512 GB SSD'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('1.5 TB', '1.5 TB'), ('1 TB SSD', '1 TB SSD'), ('2 TB SSD', '2 TB SSD'), ('3 TB SSD', '3 TB SSD'), ('4 TB SSD', '4 TB SSD'), ('not known', "Don't Know")], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='macbook',
            name='storage_capacity',
            field=models.CharField(blank=True, choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('64 GB SSD', '64 GB SSD'), ('80 GB', '80 GB'), ('120 GB ', '12O GB '), ('128 GB SSD', '128GB SSD'), ('128 GB ', '128 GB '), ('256 GB', '256 GB'), ('256 GB SSD', '256 GB SSD'), ('512 GB', '512 GB'), ('512 GB SSD', '512 GB SSD'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('1.5 TB', '1.5 TB'), ('1 TB SSD', '1 TB SSD'), ('2 TB SSD', '2 TB SSD'), ('3 TB SSD', '3 TB SSD'), ('4 TB SSD', '4 TB SSD'), ('not known', "Don't Know")], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='samsungphone',
            name='samsung_capacity',
            field=models.CharField(blank=True, choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('64 GB SSD', '64 GB SSD'), ('80 GB', '80 GB'), ('120 GB ', '12O GB '), ('128 GB SSD', '128GB SSD'), ('128 GB ', '128 GB '), ('256 GB', '256 GB'), ('256 GB SSD', '256 GB SSD'), ('512 GB', '512 GB'), ('512 GB SSD', '512 GB SSD'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('1.5 TB', '1.5 TB'), ('1 TB SSD', '1 TB SSD'), ('2 TB SSD', '2 TB SSD'), ('3 TB SSD', '3 TB SSD'), ('4 TB SSD', '4 TB SSD'), ('not known', "Don't Know")], default=None, max_length=30, null=True),
        ),
    ]
