# Generated by Django 3.0.6 on 2020-07-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceOrder', models.IntegerField(blank=True, null=True)),
                ('deviceType', models.CharField(max_length=30, null=True)),
                ('deviceCondition', models.CharField(max_length=30, null=True)),
                ('deviceQuantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquerer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30, null=True)),
                ('lastName', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('companyOrganization', models.CharField(max_length=30, null=True)),
                ('phoneNumber', models.CharField(max_length=30, null=True)),
                ('additionalInfo', models.CharField(max_length=30, null=True)),
                ('devices', models.ManyToManyField(to='sellbulk.Devices')),
            ],
        ),
    ]
