# Generated by Django 3.0.6 on 2020-07-05 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellbulk', '0001_initial_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquerer',
            name='devices',
        ),
        migrations.AddField(
            model_name='devices',
            name='inquerer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='sellbulk.Inquerer'),
            preserve_default=False,
        ),
    ]
