# Generated by Django 3.0.6 on 2020-07-05 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellbulk', '0003_auto_20200705_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devices',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='devices',
            unique_together=set(),
        ),
    ]
