# Generated by Django 2.2.10 on 2020-10-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_auto_20201016_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewards',
            name='conditon',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
