# Generated by Django 2.2.10 on 2020-10-16 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_rewards_conditon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewards',
            old_name='conditon',
            new_name='condition',
        ),
    ]
