# Generated by Django 3.0.6 on 2020-07-06 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressType', models.CharField(max_length=30, null=True)),
                ('addressLine1', models.CharField(max_length=30, null=True)),
                ('addressLine2', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('zipcode', models.CharField(max_length=30, null=True)),
                ('primaryAddress', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTradeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeReferenceNo', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('In-Progress', 'In-Progress')], max_length=30, null=True)),
                ('orderDate', models.DateField(blank=True, null=True)),
                ('lableSent', models.DateField(blank=True, null=True)),
                ('shippingLableReceived', models.DateField(blank=True, null=True)),
                ('deviceReceived', models.DateField(blank=True, null=True)),
                ('deviceReview', models.CharField(blank=True, choices=[('Ok', 'ok'), ('Requoted', 'Requoted')], default=None, max_length=30, null=True)),
                ('deviceAccepted', models.CharField(blank=True, choices=[('yes', 'yes'), ('Customer Denied', 'Customer Denied'), ('No', 'No'), ('Other', 'Other')], default=None, max_length=30, null=True)),
                ('deviceAcceptanceComment', models.CharField(blank=True, max_length=300)),
                ('paymentMethod', models.CharField(blank=True, choices=[('check', 'check'), ('Paypal', 'Paypal'), ('Amazon Gift Card', 'Amazon Gift Card'), ('Cash', 'Cash')], max_length=30, null=True)),
                ('paymentReferenceNo', models.CharField(blank=True, max_length=30)),
                ('deviceShippingMethod', models.CharField(choices=[('local-pickup', 'local-pickup'), ('USPS', 'USPS'), ('FedEx', 'FedEx'), ('UPS', 'UPS')], max_length=30, null=True)),
                ('deviceTrackingInbound', models.CharField(blank=True, max_length=30)),
                ('deviceTrackingOutbound', models.CharField(blank=True, max_length=30)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='user.UserAddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usetradeinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phoneNumber', models.CharField(max_length=30, null=True)),
                ('addresses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='user.UserAddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
