# Generated by Django 2.2.10 on 2020-07-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initia_manual_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdevicesinfo',
            old_name='user',
            new_name='trade',
        ),
    ]
