# Generated by Django 2.2.10 on 2020-10-09 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestusertradeinfo',
            name='deviceImages',
        ),
        migrations.RemoveField(
            model_name='userdevicesinfo',
            name='deviceImages',
        ),
    ]
