# Generated by Django 3.0.6 on 2020-07-06 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='addresses',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='userinfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertradeinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertradeinfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
