# Generated by Django 3.0.6 on 2020-07-16 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initia_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertradeinfo',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='user.UserAddress'),
        ),
    ]
