# Generated by Django 2.2.10 on 2020-07-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200726_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestuserdevicesinfo',
            name='usertradeinfo',
        ),
        migrations.RemoveField(
            model_name='guestuserorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='guestusertradeinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='guestusertradeinfo',
            name='userorder',
        ),
        migrations.AddField(
            model_name='userdevicesinfo',
            name='deviceNo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='GuestUserAddress',
        ),
        migrations.DeleteModel(
            name='GuestUserDevicesInfo',
        ),
        migrations.DeleteModel(
            name='GuestUserInfo',
        ),
        migrations.DeleteModel(
            name='GuestUserOrder',
        ),
        migrations.DeleteModel(
            name='GuestUserTradeInfo',
        ),
    ]
