# Generated by Django 3.0.6 on 2020-07-06 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200706_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='user.UserInfo'),
        ),
    ]
