# Generated by Django 3.0.6 on 2020-07-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usertradeinfo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertradeinfo',
            name='deviceAccepted',
            field=models.CharField(choices=[('yes', 'yes'), ('Customer Denied', 'Customer Denied'), ('No', 'No'), ('Other', 'Other')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usertradeinfo',
            name='deviceReview',
            field=models.CharField(choices=[('Ok', 'ok'), ('Requoted', 'Requoted')], default=None, max_length=30, null=True),
        ),
    ]
