# Generated by Django 3.0.6 on 2020-07-06 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200706_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to='user.UserInfo'),
        ),
        migrations.AlterField(
            model_name='usertradeinfo',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='user.UserAddress'),
        ),
    ]
