# Generated by Django 3.0.6 on 2020-07-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200703_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertradeinfo',
            name='deviceAccepted',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('Customer Denied', 'Customer Denied'), ('No', 'No'), ('Other', 'Other')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usertradeinfo',
            name='deviceReview',
            field=models.CharField(blank=True, choices=[('Ok', 'ok'), ('Requoted', 'Requoted')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usertradeinfo',
            name='paymentMethod',
            field=models.CharField(blank=True, choices=[('check', 'check'), ('Paypal', 'Paypal'), ('Amazon Gift Card', 'Amazon Gift Card'), ('Cash', 'Cash')], max_length=30, null=True),
        ),
    ]
