# Generated by Django 3.0.6 on 2020-07-04 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_auto_20200703_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useinfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertradeinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usetradeinfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
