# Generated by Django 2.2.10 on 2020-07-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_guestuseraddress_guestuserdevicesinfo_guestuserinfo_guestusertradeinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestusertradeinfo',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guestuseraddresses', to='user.GuestUserAddress'),
        ),
    ]
