# Generated by Django 2.2.10 on 2020-07-29 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200729_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestuseraddress',
            old_name='user',
            new_name='guestuser',
        ),
        migrations.RenameField(
            model_name='guestusertradeinfo',
            old_name='user',
            new_name='guestuser',
        ),
    ]
