# Generated by Django 3.0.6 on 2020-07-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200704_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertradeinfo',
            name='deviceReceived',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertradeinfo',
            name='lableReceived',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertradeinfo',
            name='lableSent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertradeinfo',
            name='orderDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
