# Generated by Django 2.2.10 on 2020-07-29 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200729_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestuserdevicesinfo',
            name='trade',
        ),
        migrations.RemoveField(
            model_name='guestusertradeinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='guestusertradeinfo',
            name='guestuser',
        ),
        migrations.DeleteModel(
            name='GuestUserAddress',
        ),
        migrations.DeleteModel(
            name='GuestUserDevicesInfo',
        ),
        migrations.DeleteModel(
            name='GuestUserInfo',
        ),
        migrations.DeleteModel(
            name='GuestUserTradeInfo',
        ),
    ]
