# Generated by Django 3.0.6 on 2020-07-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phoneNumber',
            field=models.BigIntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usertradeinfo',
            name='deviceAcceptanceComment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='usertradeinfo',
            name='deviceTrackingInbound',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usertradeinfo',
            name='deviceTrackingOutbound',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usertradeinfo',
            name='paymentReferenceNo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usertradeinfo',
            name='tradeReferenceNo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
