# Generated by Django 3.0.6 on 2020-07-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200710_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
